### ISSUE TITLE
OC-like injection of ACPI tables using DisabledAML in Clover's config.plist and relocation of ACPI Battery docs

### ISSUE THREAD

**Issue by whatnameisit** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#1]
There is a section in Clover/ACPI where addition of an ACPI table fails if there is a name match: [DisabledAML](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/Clover/EFI/CLOVER/config.plist#L50).

You can add `SSDT-RP01_PEGP.aml` in the list and give the direction to delete this entry if the user has dGPU and needs to turn it and its fan off. And also delete other entries as they do not have any effect with everything you provide in this repo.

- [config.plist](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/Clover/EFI/CLOVER/config.plist#L50)
```
		<key>DisabledAML</key>
		<array>
			<string>SSDT.aml</string>
			<string>SSDT-XCPM.aml</string>
			<string>SSDT-PluginType1.aml</string>
</array>
		<key>Comment-DisabledAML</key>
		<string>Disable other forms of CPU PM due to SSDT/Generate/PluginType=true</string>
		<key>FixHeaders</key>
```
becomes
```
		<key>DisabledAML</key>
		<array>
			<string>SSDT-RP01_PEGP.aml</string>
</array>
		<key>FixHeaders</key>
```
- [SSDT-RP01_PEGP.aml](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/Clover/EFI/CLOVER/ACPI/patched/disbale%20dGPU%20(NVIDIA%20etc.)/SSDT-RP01_PEGP.aml) goes one level up in `patched`.
- [README.aml](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/README.md#vivobooks-with-an-additional-dgpu-nvidia-geforce-940mx-mx150-etc)
```
**Clover:**

- In the file system, navigate to `EFI/CLOVER/ACPI/patched/disbale dGPU (NVIDIA etc.)` and move `SSDT-RP01_PEGP.aml` one level higher into `patched`
- via Clover Configurator: Boot > Arguments: add `-wegnoegpu`
- save & reboot
```
would be rewritten to be
```
**Clover:**

- via Clover Configurator: Boot > Arguments: add `-wegnoegpu`
- via Clover Configurator: Acpi > DisabledAML: delete `SSDT-RP01_PEGP.aml`
- save & reboot
```
or something similar.

Keep up the good work :)

**Comment by whatnameisit** [comment]
I decided to move the ACPI Battery docs to the Docs folder in the root of the repo. The docs are currently in a feature branch https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh/tree/docs/Docs and the link to the README will be https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh/blob/docs/Docs/README.md accordingly.

I think it should go in the root of your repository also because both OC and Clover are using the same Battery patch and the README should be the same for both. If you agree, I can make a pull request on this part.

**Comment by LeeBinder** [comment]
**dGPU**: yes, great input - all of that makes sense, is most streamlined and would indeed be linear with OC. I'll implement as soon as I get back to h'toshing.

Battery ReadMe.md: agreed, too - I'll move it anyway to keep our repos as parallel as possible and leave an additional pull request up to you.

**Comment by LeeBinder** [comment]
all done + included in new [11.0.1 release](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/releases/tag/11.0.1) because the ReadMe has changed/ to avoid confusion with old/new ReadMe

Because I'm uploading a .dmg with Mac meta files as release, I also added a `.gitattributes` file to / of this repo with this content:

```
# don't include any file & folder in release's source code
* export-ignore
```
:)

**Comment by LeeBinder** [comment]
@whatnameisit when you include and activate `VerifyMsrE2` in OC config.plist, then run it via OC boot menu, do you get

> This firmware has UNLOCKED MSR 0xE2 register!

? I don't - still locked after following all instructions on https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html

As per UEFITool > ifrextract, CFG Lock offset of `X510UAR-AS.310` is `0x527`, but all commands via grub with 0x527 and also 0x527 0x00 produce GUID or/ and out of range errors, and check via `VerifyMsrE2` -> still locked :(

**Comment by LeeBinder** [comment]
It's possible to have MSR 0xE2 register unlocked **_persistently_** in our VivoBooks' UEFI BIOS, even after NVRAM reset/ Setup defauts, see [[Solved - BIOS Unlock] ASUS VivoBook F510UA/X510UAR: #52](https://www.win-raid.com/t4237f54-Solved-BIOS-Unlock-ASUS-VivoBook-F-UA-X-UAR-3.html#msg114715)

**Comment by whatnameisit** [comment]
I once received locked message after I unlocked CFG with grub. Reboot fixed the message and could see unlocked. Other than that I have no problem unlocking CFG with grub on Vivobook and two other machines. I could only say check and see if you typed in the command correctly: `setup_var 0x527 0x00`. If not, the firmware would be resetting itself after each boot/reboot I think?

**Comment by LeeBinder** [comment]
just a quick note now, more later tonite: SOLVED/ unlocked :)

**Comment by LeeBinder** [comment]
I filed an issue because it's more than necessary, see https://github.com/dortania/bugtracker/issues/170

Feel free to test this yourself and file your findings there. It always sucks to be alone in an issue and get brushed off with "we don't believe you" :|

**Comment by LeeBinder** [comment]
m u u u u ch easier -> [CFGLock - unlock (MSR 0xE2)](https://www.insanelymac.com/forum/topic/344035-cfglock-unlock-msr-0xe2/) !!!

**Comment by LeeBinder** [comment]
hi @whatnameisit I added 'MSR E2 register unlock' info & material for OC & Clover, see [here](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/#unlock-the-msr-e2-register).

Next, to keep up and sync with you, I'll switch VoodooI2C from polling (back) to interrupts (🥇!)  and test locally here on my VivoBook first. I hope this will solve these sporadic erratic/ spastic/ jerky pointer movements once and for all (not too hopeful, though, because I experience them in Windows, too, no matter with which driver - tried'em all). I'll know after a few days testing.

**Comment by LeeBinder** [comment]
@whatnameisit updated and refined MSR unlock instructions incl. photos and screenshot snippets:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/blob/main/README.md#unlock-the-msr-e2-register
