### ISSUE TITLE
can you please update this for Monterey ,

### ISSUE THREAD

**Issue by arushsarna** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#10]
it would be really helpful thank you

**Comment by LeeBinder** [comment]
yes - am in the process of :)

BTW, with Clover it's easy - update kexts, update Clover, done 👍

**Comment by LeeBinder** [comment]
Monterey now also booting with latest OpenCore + latest kexts. I'm aiming to upload a beta Monday nite EU time, but might be delayed a day or two.

**Comment by LeeBinder** [comment]
@arushsarna please do as follows from your running pre-Monterey macOS:

1. update [OpenCore](https://github.com/acidanthera/OpenCorePkg) to the latest [0.7.5](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.5)
2. update all kexts to their latest versions, easiest with either [Hackintool](https://github.com/headkaze/Hackintool/releases) or [Kext Updater](https://bitbucket.org/profdrluigi/kextupdater/downloads/)
3. update [OpenCore Configurator](https://mackie100projects.altervista.org/download-opencore-configurator/)
4. download [Resources.zip](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/files/7508154/Resources.zip), unpack and replace your EFI/OC/Resources folder with the extracted
5. open your OC config.plist with OpenCore Configurator. In the Misc. section, configure like this:

   ![Bildschirmfoto 2021-11-09 um 22 44 31](https://user-images.githubusercontent.com/39203497/141010046-0c62fa32-940b-4fa8-bc95-bbe248d3f066.jpg)

6. Save and reboot
7. upgrade to macOS Monterey or install to a new APFS volume.

How did it go?

**Comment by LeeBinder** [comment]
see [macOS Monterey 12.x upgrade instructions for existing EFIs running pre-Monterey macOS](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/issues/11). You can also continue any conversation there, if needed :)
