### ISSUE TITLE
ProperTree oc snapshot breaks everything

### ISSUE THREAD

**Issue by fluffhead123** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#13]
Asus-Vivobook-X510UA?  Model 8265NGW Big Sur-11.5.2

Doing an oc snapshot in ProperTree causes kernel panic on reboot

great job on setting up the EFI. I was trying by following the official guide and had tons of problems. I do have to wonder if things are sort of rigged together or inappropriately brought over from clover. don't know why I can't do oc snapshot in ProperTree?

**Comment by LeeBinder** [comment]
Hi fluffhead123. Thanks for the kudos. I didn't know about "oc snapshots" in ProperTree until now. I have no idea what this would be for. I'm guessing: auto-applying the latest OC (files and config.plist edits) to one's OC EFI?

I always do that manually, then open config.plist in OCConfigurator, save, test-run, and just in case I experience oddities, apply required adaptions as per Dortania guide(s)/ sample plist etc. That way I'm running the latest OC release here with no probs.

Have you tried to run your VivoBook with [whatnameisit's Asus-Vivobook-X510UA-BQ490-Hackintosh EFI](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh), and after running it, tried an OC snapshot with ProperTree to it?
