### ISSUE TITLE
Can this EFI run on 14.6?

### ISSUE THREAD

**Issue by qiyx2019** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#14]
**What is your laptop model? Does it fit the specs in [README](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh/blob/master/README.md#system-specification)?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by LeeBinder** [comment]
Mojave is not covered by macOS security updates anymore. Security updates are significant. Running an out-of-date OS is a security breach and NOT recommended!

I therefore don't test Mojave anymore and can't guarantee anything. If you still think you need to run Mojave, you need to test yourself.

That said: Clover should still boot Mojave w/o any modification. OC would at least need one modification: Misc, Security, SecureBootModel -> Disabled

Please tell me why you want to boot Mojave. Running a 32bit app?
