### ISSUE TITLE
Cannot boot into 12.0 beta install USB

### ISSUE THREAD

**Issue by johnwtt** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#6]
So i used a clean image of 12.0 beta today and i can't seems to boot into the installation medium

**Comment by LeeBinder** [comment]
Hi John. Please try [whatnameisit's repo for his VivoBook X510UA-BQ490](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh) because I don't have time right now to update this repo.

**Comment by LeeBinder** [comment]
see [macOS Monterey 12.x upgrade instructions for existing EFIs running pre-Monterey macOS](https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/issues/11). You can also continue any conversation there, if needed :)
