### ISSUE TITLE
Does your laptop CPU slow down due to long hours of sleep?

### ISSUE THREAD

**Issue by Jie2GG** [LeeBinder/Asus-Vivobook-S510UA-Hackintosh#7]
Does your laptop CPU slow down due to long hours of sleep?

**Comment by LeeBinder** [comment]
@Jie2GG Would you please re-phrase your question? I honestly have no idea what you mean.

**Comment by Jie2GG** [comment]
@LeeBinder It is the frequency conversion problem of the CPU. My laptop CPU wakes up after a long period of sleep under a hackintosh. The frequency will be reduced to 500MHz and cannot be increased.

**Comment by LeeBinder** [comment]
I don't have this issue, and never heard anybody else with a S15/ S510UA(R) experience what you describe with your S5300FN.

Feel free to experiment with both EFIs of this release here, not just OpenCore but also Clover.

**Comment by Jie2GG** [comment]
好的，谢谢你的回复

**Comment by Jie2GG** [comment]
OK, thank you for your reply
